Add seller admin
Zoncovsky/Intern-Rails-App pull request #2
Opened 2022-05-29 16:53 UTC by Zoncovsky

In this branch i push new seller,admin,products model
Changed views, set up confirmations for user,seller,admin

2022-05-30 12:58 UTC, Murchibik requested changes

2022-05-30 12:58 UTC, Murchibik commented on app/models/product.rb
> +	validates :name_product, :quantity, presence: true
чому поле називається name_product? воно вже в моделі продукт, лишіть просто name

2022-05-30 12:58 UTC, Murchibik commented on config/environment.rb
> +  :user_name => 'JustARandomUser', # This is the string literal 'apikey', NOT the ID of your API key
додайте це в окремі середовища, для development.rb пошта має ходити локально, для продакшена може ходити через сендгрід

2022-05-30 12:58 UTC, Murchibik commented on config/environment.rb
> +  :user_name => 'JustARandomUser', # This is the string literal 'apikey', NOT the ID of your API key
Перенесіть це в production.rb, як ви зробили для development.rb (пошта ходить локально), для продакшена буде ходити через сендгрід

2022-05-30 12:58 UTC, Murchibik commented on config/environment.rb
> +  :password => '', # This is the secret sendgrid API key which was issued during API key creation
це має додаватись ENV змінну

2022-05-30 12:58 UTC, Murchibik commented on db/migrate/20220529113638_devise_create_users.rb
> +      t.string   :confirmation_token
Тобто ви розкоментували код в старих міграціях? які вже пройшли в вашій локальній базі? Сенс міграції в тому що нова міграція змінює структуру зі збереженням даних. Якщо ви щось додали і вже запустили цю міграцію, з новим комітом краще зробити нову міграцію яка додасть нові поля. А не робити ресет бази і з нуля запускати міграції

2022-05-31 09:39 UTC, Zoncovsky commented on db/migrate/20220529113638_devise_create_users.rb
> +      t.string   :confirmation_token
Так я дропнув стару миграцію і зробив по новій, але я зрозумів і на майбутнє буду робити як ви сказали)

2022-06-03 14:10 UTC, Murchibik approved these changes

2022-06-03 14:15 UTC, merged